[workspace]
channels = ["https://prefix.dev/conda-forge", "https://mvondomaros-lab.github.io/conda"]
name = "ThermoLab"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[pypi-options]

extra-index-urls = ["https://mvondomaros-lab.github.io/pypi"]

[tasks]

[dependencies]
jupyterlab = ">=4.5.0,<5"
pyscf = ">=2.11.0,<3"
jupyter-ruff = ">=0.3.0,<0.4"
ruff = ">=0.14.7,<0.15"
jupyterlab-lsp = ">=5.2.0,<6"
pyscf-dispersion = ">=1.3.0,<2"
geometric = ">=1.1,<2"
ipywidgets = ">=8.1.8,<9"
