[workspace]
channels = ["https://prefix.dev/conda-forge"]
name = "ThermoLab"
platforms = ["linux-64", "osx-arm64"]
version = "0.2.0"

[tasks]

[dependencies]
jupyterlab = ">=4.5.0,<5"
jupyter-ruff = ">=0.3.0,<0.4"
jupyterlab-lsp = ">=5.2.0,<6"
jupyterlab-myst = ">=2.4.2,<3"
ruff = ">=0.14.7,<0.15"
ipywidgets = ">=8.1.8,<9"
pyscf = ">=2.11.0,<3"
pyscf-dispersion = ">=1.3.0,<2"
geometric = ">=1.1,<2"
rdkit = ">=2025.9.3,<2026"
